### ISSUE TITLE
Onnodige checks aan linkerkant

### ISSUE THREAD

**Issue by MichWouters** [IgorSmirnov191/DataOef#1]
https://github.com/IgorSmirnov191/DataOef/blob/fb280b1a3f184761b48b9027bce9158a990ced69/BMI/Program.cs#L25-L37

De checks aan de linkerkant van de && zijn overbodig aangezien de vorige if daar al op controleert

**Comment by IgorSmirnov191** [comment]
Fixed in rev. 23ec5147
