### ISSUE TITLE
Fout in de berekening

### ISSUE THREAD

**Issue by MichWouters** [IgorSmirnov191/DataOef#11]
https://github.com/IgorSmirnov191/DataOef/blob/fb280b1a3f184761b48b9027bce9158a990ced69/OpDePoef/Program.cs#L27

Wat als het totaalbedrag geen rond bedrag bedraagt? 
Bijvoorbeeld 59 euro. 59 /5 = 5 weken aan 10 euro. 
Laatste 9 euro wordt zo verloren.

**Comment by IgorSmirnov191** [comment]
Fixed in rev.l38e922b9 added last weeks saldo
