### ISSUE TITLE
Onnodige variabele

### ISSUE THREAD

**Issue by MichWouters** [IgorSmirnov191/DataOef#14]
https://github.com/IgorSmirnov191/DataOef/blob/fb280b1a3f184761b48b9027bce9158a990ced69/OrakelVanDelphi/Program.cs#L47

Deze string wordt maar op 1 plaats gebruikt. Niet nodig om hier een variabele van te maken

**Comment by IgorSmirnov191** [comment]
Fixed in rev.87bed427
