### ISSUE TITLE
Best Practice: Plaats de declaratie van variabelen zo dicht mogelijk waar ze gebruikt worden.

### ISSUE THREAD

**Issue by MichWouters** [IgorSmirnov191/DataOef#15]
https://github.com/IgorSmirnov191/DataOef/blob/fb280b1a3f184761b48b9027bce9158a990ced69/OrakelVanDelphi/Program.cs#L12-L16

**Comment by IgorSmirnov191** [comment]
Fixed in rev. b4290489 with move vars to used place
