### ISSUE TITLE
Tip: Log e.Message ook naar de Console. 

### ISSUE THREAD

**Issue by MichWouters** [IgorSmirnov191/DataOef#18]
https://github.com/IgorSmirnov191/DataOef/blob/fb280b1a3f184761b48b9027bce9158a990ced69/OrakelVanDelphi/Program.cs#L54

Dit geeft meer informatie aan de gebruiker wat er misgegaan is

**Comment by IgorSmirnov191** [comment]
Fixed in rev. 89b2586b added output e.Message
