### ISSUE TITLE
Gebruik werkwoorden voor methodes

### ISSUE THREAD

**Issue by MichWouters** [IgorSmirnov191/DataOef#7]
https://github.com/IgorSmirnov191/DataOef/blob/fb280b1a3f184761b48b9027bce9158a990ced69/Feestkassa/Program.cs#L18

Gebruik duidelijke namen voor je variabelen en methodes.
De naam van een methode moet duidelijk beschrijven wat er gebeurt. 
Een betere naam is bv. BerekenTussenPrijs() { ... }

**Comment by IgorSmirnov191** [comment]
Fixed in rev. 23ec5147
