### ISSUE TITLE
Variabele kan dichter bij gebruik gedeclareerd worden

### ISSUE THREAD

**Issue by MichWouters** [IgorSmirnov191/DataOef#9]
https://github.com/IgorSmirnov191/DataOef/blob/fb280b1a3f184761b48b9027bce9158a990ced69/OpDePoef/Program.cs#L15-L19

Best practice: Declareer variabelen zo dicht mogelijk waar ze nodig zijn in een zo klein mogelijke scope.

**Comment by IgorSmirnov191** [comment]
Fixed in rev. 23ec5147
